### ISSUE TITLE
Structures alignment problem with x64

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1031] opened 2022-07-27 03:28 UTC
**Describe the bug**
Calling ProcessEntry32 (and probably many others) results in error invalid size failure (Err.LastDllError 0x18) using VBA 64-bit definitions.
Attempting to correct this manually causes a fatal runtime error 0x970FE270 or 0x86EFE960 Application defined or object defined error.

I believe this is caused by a packing issue in the compiler.

**To Reproduce**
Attempt to use CreateToolhelp32Snapshot under x64

**Expected behavior**
Correctly defined structure should be aligned correctly by compiler.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.85

**Additional context**
This is the definition I arrived at and multiple other code examples had:

```
Private Declare PtrSafe Function CreateToolhelp32Snapshot Lib "kernel32" (ByVal dwFlags As TH32CS_Flags, ByVal th32ProcessID As Long) As LongPtr
Private Declare PtrSafe Function Process32First Lib "kernel32.dll" (ByVal hSnapshot As LongPtr, lppe As PROCESSENTRY32) As Long

Private Type PROCESSENTRY32
    dwSize As Long
    cntUsage As Long
    th32ProcessID As Long
    'pack1 As Long
    th32DefaultHeapID As LongPtr
    th32ModuleID As Long
    cntThreads As Long
    th32ParentProcessID As Long
    pcPriClassBase As Long
    dwFlags As Long
    szExeFile As String * 260
    'pack2 As Long
End Type
```

I'm attaching the current version of my project that's using this; it's set to call a routine that calls this API in Form_Load, so just needs to be started (under x64 mode). Routine itself in modProcInfo.twin.

`
[TBEventTrace64.zip](https://github.com/twinbasic/twinbasic/files/9194795/TBEventTrace64.zip)

**Comment by fafalone** [comment] 2022-07-27 03:51
I uncommented the first pack and didn't get an error, and successfully enumerated processes.

The compiler appears to be padding the end of structures to 8-byte alignment, because it's 564 bytes with the single pad, but not doing intermediate padding.
th32DefaultHeapID must be at offset 0x16 under x64, not 0x12..

**Comment by WaynePhillipsEA** [comment] 2022-07-27 04:32
I suspect the problem is not the packing, as we have extensive tests in this area.  Are you using `LenB` rather than `Len` for determining the length?

**Comment by fafalone** [comment] 2022-07-27 04:39
Yes, but that works under both 32bit, and 64bit VBA according to multiple example code I found (I don't have Office installed, but e.g. [here](https://rstforums.com/forum/topic/38769-taskmanager-runs-on-64-bit-excel/)); because it's an ANSI call, where you generally use Len(), compared to Unicode calls (there is Process32FirstW), where you use LenB. 

And if that was the problem I don't see how unpacking only the 1st padding Long would resolve the issue.

**Comment by WaynePhillipsEA** [comment] 2022-07-27 04:47
The offsets and lengths are all matching to VBA x64:
```
Dim p As PROCESSENTRY32
    Debug.Assert VarPtr(p.dwSize) - VarPtr(p) = 0
    Debug.Assert VarPtr(p.cntUsage) - VarPtr(p) = 4
    Debug.Assert VarPtr(p.th32ProcessID) - VarPtr(p) = 8
    Debug.Assert VarPtr(p.th32DefaultHeapID) - VarPtr(p) = 16
    Debug.Assert VarPtr(p.th32ModuleID) - VarPtr(p) = 24
    Debug.Assert VarPtr(p.cntThreads) - VarPtr(p) = 28
    Debug.Assert VarPtr(p.th32ParentProcessID) - VarPtr(p) = 32
    Debug.Assert VarPtr(p.pcPriClassBase) - VarPtr(p) = 36
    Debug.Assert VarPtr(p.dwFlags) - VarPtr(p) = 40
    Debug.Assert Len(p) = 300
    Debug.Assert LenB(p) = 568
```

**Comment by bclothier** [comment] 2022-07-27 04:54
Linking for reference: #936

**Comment by fafalone** [comment] 2022-07-27 04:57
Hmm, I'm at a loss to explain how could 4 bytes resolve the problem then.

Commenting out the 1st pad again, and substituting LenB, appears to also work... I'll check whether that breaks 32bit, but I don't know why people have apparently had success with it in VBA then... and why I can add or remove 4 bytes and not mess up szExeName either.

**Comment by fafalone** [comment] 2022-07-27 04:59
@bclothier, is it an incorrect use though? ANSI is 1 byte per character, it's an ANSI call, shouldn't the character length be what you report?

**Comment by WaynePhillipsEA** [comment] 2022-07-27 05:17
Note that for the ANSI version, the real length on x64 would be 304 (szExeFile starts at offset 44, plus the 260 chars equals 304).  That happens to also be `Len(p) + 4`, so explains why the extra 4 allowed it to work.

The API call is just checking whether the length is a minimum of 304 bytes for the ANSI version.  Since you're using the ANSI version of Process32First, technically neither `Len` or `LenB` will give you the "correct" value of 304, but the API won't complain provided the value is at least 304.

**Comment by WaynePhillipsEA** [comment] 2022-07-27 05:20
To correct the problem, you'd need to change that fixed length string into a byte array: `szExeFile(1 To 260) As Byte`, then `LenB` will give you the correct answer of 304 on x64.

**Comment by WaynePhillipsEA** [comment] 2022-07-27 05:25
`Len()` only accounts for the length of the individual elements, and so often needs changing to `LenB()` on 64-bit due to the extra alignment/padding.  In cases involving UDT members of fixed length strings being passed to API calls, this change does cause problems due to `LenB` giving you the size of the unicode version of the UDT.

**Comment by WaynePhillipsEA** [comment] 2022-07-27 05:32
What we could really do with, is a version of `LenB` that gives us the real length of the ANSI version of the UDT, specifically for use with ANSI API calls.   This could ease transition from 32-bit, since neither `Len` nor `LenB` are always correct when fixed length strings are involved.

`Len()` -> gives the combined length of the individual elements
`LenB()` -> gives the total UDT length (Unicode)
`LenBAnsi()` -> gives the total UDT length (ANSI)

**Comment by fafalone** [comment] 2022-07-27 07:22
Ok I think I see the issue-- The VBA samples I was looking at both had incorrect declares, padding pcPriClassBase, which as a LONG, should have stayed as a single entry right?, which gave them the same extra 4 bytes my pad did. Apologies for opening an issue incorrectly.

Still a little confused about how it doesn't result in bleeding into the 1st 4 characters of the string in one of the two scenarios, but I can pursue that inquiry elsewhere.

**Comment by WaynePhillipsEA** [comment] 2022-07-27 07:29
No worries, glad you got it sorted.  I'll close this then.

**Closed by WaynePhillipsEA** 2022-07-27 07:29 UTC
