### ISSUE TITLE
SelStart etc not Supported

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1250] opened 2022-10-12 18:19 UTC
**Describe the bug**

Missing Functionality

Text and Combo boxes do not yet support SelStart, SelLength and SelText

These are supported in VB6

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [146]

**Additional context**

**Comment by WaynePhillipsEA** [comment] 2022-10-13 05:09
Thanks.  I have instead added these to the UI Controls thread: https://github.com/twinbasic/twinbasic/issues/1188
(somehow they got missed there).

I'll close this so that we keep all the controls stuff together.

**Comment by WaynePhillipsEA** [comment] 2022-10-13 09:38
Just looking at this.   So `SelStart`/`SelLength` and `SelText` are all implemented already.  What issues were you encountering?

I see one immediate issue is that when tabbing into a TextBox, tB selects the whole content when focusing it, which is not the same behaviour as VBx.

**Comment by dmrvb** [comment] 2022-10-13 09:59
Dunno, I have got myself very confused. Made a little test prog and could not see SelStart in the itellisense dopdowm, but now I can.
Still getting an "unrecognised member" error when I import a project from VB. I will investigate more later today (if you don't get there first), but I think its the control array that is the issue.....**no SelStart on Control Arrays?????**
As to your comment about selection when tabbing, as far as I can see the selection of text in multiple controls when activating a form in VB is somewhat random, hence I use SelStart/SelLength to make things better behaved

**Comment by WaynePhillipsEA** [comment] 2022-10-13 10:04
I've just added a property `TabFocusSelectAll` (boolean, default False) coming in the next release.  I will check SelStart etc on control arrays.

**Comment by WaynePhillipsEA** [comment] 2022-10-13 10:06
Checked textbox control array... can't see any problem there.  If you can reduce down to a sample, I'll certainly take a look.  Thanks!

**Comment by WaynePhillipsEA** [comment] 2022-10-13 10:10
Ah OK, it's just the ComboBox that's missing these properties by the looks of it.

**Comment by Kr00l** [comment] 2022-10-13 10:10
@WaynePhillipsEA something other is at play also. Because my VBCCR17.TextBoxW does not get all focus on tab in VB6. But in tB it receives all focus. (?)

**Comment by WaynePhillipsEA** [comment] 2022-10-13 10:13
@Kr00l tB currently issues WM_GETDLGCODE to the control and checks for the DLGC_HASSETSEL flag.  If it returns it, then it selects the contents.  It looks like VBx doesn't do that at all.

**Comment by Kr00l** [comment] 2022-10-13 10:15
@WaynePhillipsEA  So it would be better as a Form property ?

**Comment by WaynePhillipsEA** [comment] 2022-10-13 10:18
@Kr00l Yes, actually that makes more sense

**Comment by WaynePhillipsEA** [comment] 2022-10-13 10:23
For the name of the form property, is `TabFocusSelectContent` clear enough?

**Comment by Kr00l** [comment] 2022-10-13 10:33
`TabFocusAutoSelect` is my suggest...

However, having the Form property doing the check at all is one thing.

For the TextBox control we could offer an additional property which indicates if `DLGC_HASSETSEL` will be removed the return flag on the edit's `WM_GETDLGCODE` or not. That would be ultimate flexible.

**Comment by WaynePhillipsEA** [comment] 2022-10-13 10:39
So `Form.TabFocusAutoSelect` as a master ON/OFF switch, and then `TextBox.TabFocusAutoSelect` individually, if the master switch is ON.  Did I get that right?

**Comment by Kr00l** [comment] 2022-10-13 10:45
> So `Form.TabFocusAutoSelect` as a master ON/OFF switch, and then `TextBox.TabFocusAutoSelect` individually, if the master switch is ON. Did I get that right?
> 
> So `Form.TabFocusAutoSelect` would default to False and `TextBox.TabFocusAutoSelect` can default to True.

That sounds good.
Yes..
 Form should be False (VB6 compat)
 TextBox should be True by default (no alteration)

**Comment by wqweto** [comment] 2022-10-13 11:11
VB's TextBox not auto-selecting on keyboard focus only (mouse activation should never auto-select) is actually a bug IMO.

The ComboBox does it and it makes no sense for TextBox not to. I'm reimplementing this standard Windows control behavior in each and every project on mine just not to surprise end-users in unexpected ways.

Another nuisance is shortcuts like `Ctrl+A` not working. I suppose removing `Ctrl+C`/`Ctrl+V` would have been met with all the rage in '98 :-))

**Comment by WaynePhillipsEA** [comment] 2022-10-13 11:12
@wqweto from BETA 148 you'll be able to just set the Form.TabFocusAutoSelect property to True, and then you'll get the more expected behaviour.

**Comment by wqweto** [comment] 2022-10-13 11:15
> @wqweto from BETA 149 you'll be able to just set the Form.TabFocusAutoSelect property to True, and then you'll get the more expected behaviour.

Good! Now make it `True` by default to educate the masses :-)) I'm pretty sure most will fall into "The Trap of Success" if set `True` by default. And end-users will love it!

**Comment by sokinkeso** [comment] 2022-10-13 11:20
I agree with @wqweto and Wayne. and BTW, the checkbox and opionbutton do not have the dotted rectangle to show that got the focus.

**Comment by Kr00l** [comment] 2022-10-13 11:26
> Well yes, that is an option. We could then set it to False automatically only for imported forms. @Kr00l, what do you think?

@WaynePhillipsEA That's a difficult question. Beside the excitement from @wqweto , it is a behavior change. (100% !!!111)

Having a other default property for imported stuff is ugly, because then you start adding new stuff and then you have suddenly two different behaviors.

**Comment by rexxitall** [comment] 2022-10-13 11:32
From the point of a game developer or fan of nice looking contrals i would like to have color settings for the checkframe, the hook and the area of the hook. Looks ugly and can not be changed in vbx :/ Sure they are optional but would not harm existing projects. I really hate all that gray stuff in the controls you can not change. in the 80ties there was a german song whith the line "Eure grauen Zellen sollen Farben erhellen", (Your gray cells should be illuminated by colors). I do not want to know how many peoples subcallssing or even write ocx just to get rid the gray...

**Comment by wqweto** [comment] 2022-10-13 11:47
> Having a other default property for imported stuff is ugly, because then you start adding new stuff and then you have suddenly two different behaviors.

True. If VBP import would change the value of a Form property it should be named `CompatibilityMode = True` or similar.

Let's leave `TabFocusAutoSelect = False` in all cases for now. It's more than enough such property is implemented in TB to begin with.

**Comment by rexxitall** [comment] 2022-10-13 12:04
just if you do not have a "strict switch". Which could also be used to mark such code in the editor.

**Comment by sokinkeso** [comment] 2022-10-13 12:41
> offer the graphical versions of these, so that is where we can

I was pretty sure that you have something in mind about that.
Thanks Wayne.

**Comment by WaynePhillipsEA** [comment] 2022-10-13 13:03
Interesting @Kr00l!  Thanks for your input as always.

I'm open to suggestions on the properties for this.   I definitely think it's worth adding some options here.  The missing focus rectangles in particular will be a common request from VB6ers, I think.

**Comment by dmrvb** [comment] 2022-10-13 13:42
This is all very good stuff, there are loads of things about the VB GUI that could be improved in tB. Its tempting to do them now while Wayne is working on this, but its probably better to get to a v1 release that imports and compiles a VB project, and then go back and improve the GUI in the future???.
I've written some little test progs but I really want to get the big apps compiled to see how the GUI performs before producing a list of eenhancement requests.

**Comment by WaynePhillipsEA** [comment] 2022-10-13 13:55
@dmrvb It was a behaviour difference between tB and VB6 that needed fixing anyway.  So whilst I was in that area of code it totally makes sense to add an extra property (or two) to allow better control over the behaviour.   It's a small thing to implement when you're already in that area of code.

Regarding the focus rectangles, again that will also be considered a behaviour difference, and so needs fixing anyway.

**Comment by Kr00l** [comment] 2022-10-13 15:47
> Interesting @Kr00l! Thanks for your input as always.
> 
> I'm open to suggestions on the properties for this. I definitely think it's worth adding some options here. The missing focus rectangles in particular will be a common request from VB6ers, I think.

To be honest, maybe tB should just show the focus rects and accelerator keys right at Form's initialization. So no property.. and everyone will be happy. ;)

**Comment by dmrvb** [comment] 2022-10-13 17:12
> @dmrvb It was a behaviour difference between tB and VB6 that needed fixing anyway. So whilst I was in that area of code it totally makes sense to add an extra property (or two) to allow better control over the behaviour. It's a small thing to implement when you're already in that area of code.
> 
> Regarding the focus rectangles, again that will also be considered a behaviour difference, and so needs fixing anyway.

Its all goood.. If the first release is both VB compatible and also has lots of enhancements then you win twice over. I hope that tB can be seen as both something to keep VB code alive, but also as a modern evolving language.

**Comment by Kr00l** [comment] 2022-10-14 13:04
@WaynePhillipsEA maybe we create a seperate issue for that. But regarding the UI state (keyboard cues) I found interesting information.

`IsDialogMessage() sends WM_CHANGEUISTATE, which needs to be passed on to the default window procedure. The default window procedure propagates the message to its parent, until it finds a window that has no parent. The default window procedure of that window then converts this message to a WM_UPDATEUISTATE message, that's passed to all child windows. You can call IsDialogMessage() for any window, not just dialogs`
[Why am I not getting WM_UPDATEUISTATE?](https://stackoverflow.com/questions/42637364/why-am-i-not-getting-wm-updateuistate)

Is tB using the IsDialogMessage ? Because then the dialog manager takes care of the UI states.
Because after a thought we should keep it system conform. Means if only `SPI_GETKEYBOARDCUES` is TRUE then show focus rects and accelerator keys immediately, otherwise only if TAB or ALT key was pressed once, but then for all controls. And that seems to be taken care of by the IsDialogMessage function.

**Comment by WaynePhillipsEA** [comment] 2022-10-14 13:22
@Kr00l No, we don't use IsDialogMessage, but a custom implementation that accounts for various VB6 quirks.  Thanks for the extra information, that helps a lot.

**Comment by WaynePhillipsEA** [comment] 2022-10-15 07:30
In BETA 149;
ComboBox SelStart / SetLength / SelText is now supported.
TabFocusAutoSelect was also added to Form and TextBox as discussed in this thread.

The focus rectangle issues discussed will be looked at for next release.

**Closed** 2023-06-02 19:17 UTC
