### ISSUE TITLE
Office Add-in Events

### ISSUE THREAD

**Issue by AlanSkyNet** [twinbasic/twinbasic#1088] opened 2022-08-08 09:55 UTC
Hello,

We are trying to port a shared Office COM Add-in to support communication with Word, Excel and Outlook. 
When we create a private Application object with events, we set it after being called by the OnConnection event
but after that we don't receive any events (32/64bits). 
Is that a known issue or have we forgotten something ?
Thanks,
Alan

**Comment by mwolfe02** [comment] 2022-08-12 03:43
I tried in vain to get this to work tonight, too.  Here are the steps to reproduce my (failed) attempts:

1. Start with Sample 5. MyCOMAddin
2. Add a reference to the Excel 1x.0 Object Library
3. In MyCOMAddin class module, change the line: `Private applicationObject As Object` to `Private WithEvents ExcelApp As Excel.Application` (do a find and replace for the four instances of `applicationObject`)
4. Add the following event handling lines at the bottom of the "MyCOMAddin" class module:

```    
Private Sub ExcelApp_WorkbookOpen(ByVal Wb As Workbook) Handles ExcelApp.WorkbookOpen
    MsgBox "You've opened a workbook!", vbInformation, "Hello from twinBASIC"
End Sub
    
Private Sub ExcelApp_NewWorkbook(ByVal Wb As Workbook) Handles ExcelApp.NewWorkbook
    MsgBox "You've opened a new workbook!", vbInformation, "Hello from twinBASIC"
End Sub
```

What am I missing?

P.S.  FWIW, I've made this sort of functionality work with .NET via the [NetOffice Framework](https://netoffice.io/).

**Comment by WaynePhillipsEA** [comment] 2022-08-17 07:27
Thanks for reporting this issue.  The problem has been identified, and will be rectified within a few days.

Excel calls it's event handlers through IDispatch::Invoke which is quite normal, but passes arguments using named argument DISPIDs that are known at compile-time, which is more unusual.  tB does support named arguments, but the DISPIDs we assign to them are not matching the ones defined in the Excel type library (or assigned automatically via MIDL).  Since Excel doesn't query for the DISPIDs at runtime (through IDispatch::GetIDsOfNames), the IDispatch::Invoke call silently fails due to the mismatched DISPIDs for the passed in arguments.

**Comment by wqweto** [comment] 2022-08-17 08:23
Now this is an implementation detail that hardly anyone knows :))

**Comment by WaynePhillipsEA** [comment] 2022-08-18 07:17
Fixed in BETA 94, thanks for reporting!

**Closed by WaynePhillipsEA** 2022-08-18 07:17 UTC
