### ISSUE TITLE
Evaluation order different to VB6 P-Code

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1040] opened 2022-07-27 09:46 UTC
**Describe the bug**
Evaluation order different to VB6 P-Code

**To Reproduce**
1. Play with the attached examples VB6 vs. tB
[ExOrder1.zip](https://github.com/twinbasic/twinbasic/files/9197119/ExOrder1.zip)

**Expected behavior**
Same behavior.

**Screenshots**
![image](https://user-images.githubusercontent.com/88059532/181216878-2c736f9c-ac24-49db-8dc4-156696939fe8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC 86

**Comment by WaynePhillipsEA** [comment] 2022-07-27 10:27
Still looking into this, thanks for reporting.  Initially, it looks like if either the LHS or RHS evaluates to a floating point type (Single/Double/Date), then the evaluation order is swapped (i.e. RHS is evaluated before the LHS), except if either side is a Variant.

**Comment by WaynePhillipsEA** [comment] 2022-07-27 10:57
correction: if either the LHS or RHS evaluates to a floating point type (Single/Double/Date) **_or a String type_**, then the evaluation order is swapped (i.e. RHS is evaluated before the LHS), except if either side is a Variant.

**Comment by WaynePhillipsEA** [comment] 2022-07-27 11:38
further correction: whilst the above description roughly encapsulates the VBx implementation, it's just not that simple.  There are also many edge cases that don't fit (.e.g. sometimes the Currency type also causes the swap, but only if on the RHS, and Booleans also have edge cases).

Basically, VBx is a mess here.  I'm building a table so that I can make tB copy the VBx behaviour as closely as possible.

**Comment by KarlSevenSeven** [comment] 2022-07-27 11:53
Smaller example:

```
Option Explicit

Dim CurProc As String

Dim md      As String

Sub DL(ByVal Nr As Long, _
   Optional Text As Variant)

md = md & Text & vbLf

End Sub

Sub main()

Dim OK As Boolean

CurProc = "Main"

If Min(0, 0) <= Max(0, 0) + 1 Then OK = (Max(0, 0) + 1 >= Min(0, 0))

DL 1, "OK = " & OK

MsgBox md

End Sub
Function Max(ByVal X As Double, ByVal Y As Double) As Double

DL 1, "Entered - " & "Math.Max" & "| CurProc: " & CurProc
CurProc = "Math.Max"

Max = IIf(X > Y, X, Y)

End Function

Function Min(ByVal X As Double, ByVal Y As Double) As Double

DL 1, "Entered - " & "Math.Min" & "| CurProc: " & CurProc
CurProc = "Math.Min"

Min = IIf(X < Y, X, Y)

End Function
```

**Comment by WaynePhillipsEA** [comment] 2022-07-27 12:01
@KarlSevenSeven I've wrote all the tests needed to cover this. I'll implement the changes tomorrow.

**Comment by bclothier** [comment] 2022-07-27 12:06
I'm just curious - I wonder how that will work out when we start introducing LLVM and optimizations? If it shouldn't matter when optimizing, then why would it matter when compiling to p-code?

**Comment by WaynePhillipsEA** [comment] 2022-07-27 12:22
Safe optimizations are not allowed to reorder things that would cause a change in behaviour.  Generally, calling functions in a different order would be a change of behaviour, unless you can prove that changing the order doesn't change the behaviour (e.g. by examining the full called function implementation in whole program optimization).

With VB6 p-code compilation differing with VB6 native-code compilation even with all optimizations off, we can only assume that the order of execution in VBx is considered to be not strictly defined.  Further evidence for that is the behaviour described above, where in p-code compilation, the order of execution varies depending on the data types involved in the evaluation.

So when it comes to LLVM, given only safe optimizations, it will behave the same as our non optimizing compiler, unless we tell it otherwise.

**Comment by wqweto** [comment] 2022-07-27 12:45
@KarlSevenSeven  Btw, how does your source code work ok when p-code compiled vs native compiled, provided that both of these targets change order of execution substantially? Why would TB's change in order of execution be the culprit for your source code not working?

If the component is still not working in TB then the problem must be somewhere else, there is probably another bug which trips it up.

But now Wayne has a long list of LHS vs RHS order of execution that he has to implement and then this list will change for each of VB compile targets and optimization options, so this looks like a Sisyphus undertaking IMO and complete waste of effort.

**Comment by KarlSevenSeven** [comment] 2022-07-27 13:47
> @KarlSevenSeven Btw, how does your source code work ok when p-code compiled vs native compiled, provided that both of these targets change order of execution substantially?

How should I know?
Regarding the large ActiveX source, I gave up on it and won't come back to it for some time or probably never.
I can't deliver useful info.
No chance - case finally closed.

> Why would TB's change in order of execution be the culprit for your source code not working?

I can't know.
Also I do report what I observe only.
I never said that the evaluation order is the root of the AX problem.

> If the component is still not working in TB then the problem must be somewhere else, there is probably another bug which trips it up.

Probably yes.
Perhaps not.

> But now Wayne has a long list of LHS vs RHS order of execution that he has to implement and then this list will change for each of VB compile targets and optimization options, so this looks like a Sisyphus undertaking IMO and complete waste of effort.

It is his decision to work on that.
He aims for 100% compatibility, so I understand it.
And if he wants to waste time, he is free to do that as well.
But I don't think he does so.

**Comment by KarlSevenSeven** [comment] 2022-07-27 13:59
> a long list of LHS vs RHS order of execution

I'm more worried about the performance when the table comes into the game.
We will see.

**Comment by WaynePhillipsEA** [comment] 2022-07-27 15:23
> But now Wayne has a long list of LHS vs RHS order of execution that he has to implement and then this list will change for each of VB compile targets and optimization options, so this looks like a Sisyphus undertaking IMO and complete waste of effort.

I now suspect we will just implement it as per the VBx p-code (IDE) rules, which are deterministic, and that will be the end of it.

Given what we now know, any code that relies on the order of function call executions within expressions in VB6 is going to be flakey, and so I'd prefer to have something that is at least consistent.  It's not much work to match the VB6 p-code behaviour, and this will increase backwards compatibility, even if only a fraction.

**Comment by bclothier** [comment] 2022-07-27 15:33
I'm wondering whether the optimizations for VB6 were provided for by MSVC compiler? Meaning they'd have the same changes if it was C++ compiled under VC++ v6?

**Comment by WaynePhillipsEA** [comment] 2022-07-27 15:41
@bclothier most probably, yes.  And that might explain it, because in C++ (prior to C++17), the order of execution of parts of and expression were not guaranteed (see https://en.cppreference.com/w/cpp/language/eval_order).

**Comment by bclothier** [comment] 2022-07-27 15:46
I don't know enough about LLVM but if it supports using the legacy C++ optimization rules, that would be an option to allow tB to compile to same output as one of the VB6's optimized outputs.

**Comment by fafalone** [comment] 2022-07-27 19:22
I compiled the VB project to native code and got the same result as p-code (both with optimized/fast and no optimization). 

Perhaps someone can clarify-- doesn't TB compile to native code, and given that case, should be matching VB6 native code where that does differ from p-code?

**Comment by WaynePhillipsEA** [comment] 2022-07-27 19:43
@fafalone more info in earlier thread #845

In short, in VBx the order of evaluation of function calls in an expression can be different between p-code compilation and native code compilation.  As such, we can consider the evaluation order to be undefined, or 'not guaranteed'.

Furthermore, due to compiler optimizations, the evaluation order in native code is not necessarily deterministic.  In p-code there are virtually no optimizations, and so the evaluation order is deterministic.  As such, it can be imitated easily.   

Even if we allow LLVM to re-order these function calls during optimization passes, there's no guarantee the order it chooses will ever match the order chosen by the 20+ year old VB6 compiler.

Trying to match the output of one optimizing compiler with another completely different optimizing compiler is a non-starter.  Therefore the only sane option is to match the p-code compiler, which is deterministic in nature.

**Comment by WaynePhillipsEA** [comment] 2022-07-28 07:06
BETA 87 should fix this issue. @KarlSevenSeven  I'll leave this open in case you find any more to report, so just close it when you're done.  Thanks.

**Comment by KarlSevenSeven** [comment] 2022-07-28 09:09
> > a long list of LHS vs RHS order of execution
> 
> I'm more worried about the performance when the table comes into the game. We will see.

All is fine regarding performance:
```
VB6 EXE P-Code: 420 msec.
VB6 EXE N fast: 230
         tB 86: 275
         tB 87: 280
```
[EvalPerformance.zip](https://github.com/twinbasic/twinbasic/files/9207609/EvalPerformance.zip)

**Comment by wqweto** [comment] 2022-07-28 09:52
> @bclothier most probably, yes. And that might explain it, because in C++ (prior to C++17), the order of execution of parts of an expression were not guaranteed (see https://en.cppreference.com/w/cpp/language/eval_order).

Btw, execution order is [guaranteed for short-circuit expressions in C/C++](https://stackoverflow.com/questions/628526/is-short-circuiting-logical-operators-mandated-and-evaluation-order) so that `if(a() && b(&result) && result > 0)` is executed left to right and `result` is populated before reaching 3-rd expression.

Unfortunately due to booleans being -1 and 0 so that logical operator can be implemented as bitwise ones I suspect that VB6 compiler emits bitwise `&` and `|` on `If A() And B() Then` expressions so that there is no short-circuits are allowed and as a consequence the underlying C compiler is allowed to reorder function calls. Ouch!

TB supports `AndAlso` + `OrElse` so these must preserve execution order just like in C/C++ and given the circumstances makes much more sense to use in any codebase.

**Comment by WaynePhillipsEA** [comment] 2022-07-28 10:26
Yeah for short circuiting it has to be, and I agree the boolean logic in VB is likely the root cause that allows the function call reordering in native code builds.

Also I think we should definitely offer a warning/hint for use of `And`/`Or` in cases where it is obvious that `AndAlso`/`OrElse` would be more appropriate.

**Closed** 2022-08-19 07:15 UTC
