### ISSUE TITLE
Randomly access violation

### ISSUE THREAD

**Issue by bodrusG** [twinbasic/twinbasic#1519] opened 2023-03-05 19:20 UTC
Hi , sometimes when moving objects on the form this error occurs and you have to kill Twinbasic to exit.
Unfortunately I am unable to replicate the behavior which seems random

![immagine](https://user-images.githubusercontent.com/124681792/222981031-1de74eef-03ec-42b2-b789-5a0be78089e6.png)

tb261

**Comment by WaynePhillipsEA** [comment] 2023-03-05 19:26
When this next happens, could you check the task manager and see if the twinbasic_win32.exe has reached   near the 2GB memory usage (it will usually show about 1.7GB n talk manager before failures occur).

**Comment by bodrusG** [comment] 2023-03-05 20:02
hi this is a screenshot of taskmanager , 
besides twinbasic only vlc was active playing an mp3


![immagine](https://user-images.githubusercontent.com/124681792/222982942-d2c189c8-29c3-44c2-9385-1e8e8876905a.png)
![immagine](https://user-images.githubusercontent.com/124681792/222982969-5338a203-87e9-4a0b-800a-895774909450.png)
![immagine](https://user-images.githubusercontent.com/124681792/222982988-e91791f9-1508-4112-8c1f-77a2502fbf2a.png)

**Comment by WaynePhillipsEA** [comment] 2023-03-05 20:07
Thanks, that confirms it is not a memory issue.

Unfortunately, until we can get steps to reproduce the issue, this will be difficult to solve.   If you find any pattern to the problem/behaviour, please do let us know.

**Comment by bodrusG** [comment] 2023-03-05 20:25
I realize the difficulty, the last time it happened I was doing the resizing of a frame inside another frame, but other times also while writing the code and parsing to attribute the colors. It seems as if the memory slowly fills up until the next operation whatever it is causes the error, but it is clear that mine is only a guess

**Comment by bodrusG** [comment] 2023-03-05 20:42
now it happened while the intellisense was listing the members of a udt variable

**Comment by WaynePhillipsEA** [comment] 2023-03-05 20:51
I think the auto-restart-on-crash feature may be broken in the latest builds.  I will be looking at this tomorrow.

**Comment by bodrusG** [comment] 2023-03-05 20:54
who better than you can get the right idea :-)

**Comment by WaynePhillipsEA** [comment] 2023-03-06 06:34
The most important part of the problem here is that the compiler should be restarting gracefully automatically when the crash occurs, and this was happening until recent changes (since BETA 259).  This should now be fixed in BETA 263.

Please let me know if this resolves the issue for you.

**Comment by bodrusG** [comment] 2023-03-06 09:13
ok ,thanks.. i 'll try

**Comment by bodrusG** [comment] 2023-03-06 09:36
i think it work .. the error  of access violation fire again but the compiler restart correctly

![immagine](https://user-images.githubusercontent.com/124681792/223072267-6d71de46-a235-46fd-b8a0-bffec99cc16f.png)

**Comment by WaynePhillipsEA** [comment] 2023-03-13 06:19
Thanks for confirming.  I'll close this then, as the graceful restart is the most important part for now.  Thanks!

**Closed by WaynePhillipsEA** 2023-03-13 06:19 UTC
