### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by bodrusG** [twinbasic/twinbasic#1476] opened 2023-02-07 11:47 UTC
**Describe the bug**
 I have a projet (exe file) with no error and i can run it in debug mode , but when make exe i have this  error

![immagine](https://user-images.githubusercontent.com/124681792/217236055-0982c956-6c6f-4495-b5f0-f2f1fb63d346.png)

the form reported in error log  is so simple that i cant imagine why cause error

![immagine](https://user-images.githubusercontent.com/124681792/217236435-eba2e9a3-52b0-49b3-be20-a2930c7cf086.png)

twinbasic 237
windows10 italian

thanks a lot for your incredible work !

**Comment by fafalone** [comment] 2023-02-07 12:32
A lot of issues with type libraries have been fixed recently; you should try building in the newest version (Beta 243 as of this comment).

**Comment by bodrusG** [comment] 2023-02-07 12:56
yes .. when i run in debug mode the project cant run in 2423 but in 237  its ok

![immagine](https://user-images.githubusercontent.com/124681792/217250654-37aa70ee-aa67-4a54-b53d-57ba05e67dad.png)

**Comment by fafalone** [comment] 2023-02-07 12:57
Looks like the same label error I posted in the Discord:
https://discord.com/channels/927638153546829845/1071277833017622528

Same error, same line.

**Comment by bodrusG** [comment] 2023-02-07 13:00
many thanks .. i have other question but i will report it later..i know your work is hard .. ,

**Comment by fafalone** [comment] 2023-02-07 13:02
> Apologies; that bug report didn't catch my attention. I'm now onto it...

No problem, only so many hours in a day and I know you're laser focused on UserControls right now 👍

**Comment by WaynePhillipsEA** [comment] 2023-02-07 13:03
OK, the Label error is now fixed in the release coming later today.   Could you confirm that the actual build succeeds in BETA 243?  (so you don't get the type library error as you encountered in the earlier releases)

**Comment by bodrusG** [comment] 2023-02-07 13:03
unfortunattelly  in 243 i have the same error on compile exe ...

**Comment by bodrusG** [comment] 2023-02-07 13:06
i hve no problem to give you the project but it use a external dll com writed in dot net  , you neet it also wher  i can post the project file ?

**Comment by WaynePhillipsEA** [comment] 2023-02-07 13:08
Yes, both please.  You can post it on here as a ZIP, or over on discord if you prefer.

**Comment by bodrusG** [comment] 2023-02-07 13:15
you need also thi ini file in appdata roaming .. change the path of the csv file for run project ..
[VSScriptGiochiClient.zip](https://github.com/twinbasic/twinbasic/files/10675319/VSScriptGiochiClient.zip)

**Comment by WaynePhillipsEA** [comment] 2023-02-07 13:22
Thanks.  I managed to reproduce the error, so I will look into it.

**Comment by WaynePhillipsEA** [comment] 2023-02-07 13:27
The problem here is that you have an overloaded member, AlimnetaLista:

`Sub AlimentaLista(aVoci() As String)`
`Sub AlimentaLista(aVoci() As String, aItemdata() As Long)`

Overloaded members are fine inside tB, but can't be exposed via COM.  There are a few different ways to fix this, but the easiest is to change `Class frmScegliOpzione` into `Private Class frmScegliOpzione`, that way the form will not try to be exposed via COM.

**Comment by bodrusG** [comment] 2023-02-07 13:30
thanks ,  , i try your suggestion but i dont want to expose nothing to com , from twinbasic project.maybe there ise some configuration for it ? 
Is the twinbasic project that use the com dll write in dotnet.
but if it work  for mi its ok ..

**Comment by WaynePhillipsEA** [comment] 2023-02-07 13:32
At the moment tB generates a COM type library even for Standard EXE projects.   It doesn't need to, and it shouldn't... so I will get that issue fixed, and then this error won't occur in future.

**Comment by bodrusG** [comment] 2023-02-07 13:33
it work ! Thanks but now i have question :-)  why the issue is only with that form .. there are other form like it in project ...

**Comment by WaynePhillipsEA** [comment] 2023-02-07 13:34
Other forms that have overloaded members?  Which ones?

**Comment by bodrusG** [comment] 2023-02-07 13:44
ah sorry no ... but i thake the oppotunity to ask you why the  optional parameter sCaption  seem remain default value although if i pass another value ..

the call
   k = ScegliOpzioneMenu (aVoci, "test")
         
dont set the caption of the form to test .. it remain de default value of the function 


![immagine](https://user-images.githubusercontent.com/124681792/217261568-5f999298-60f5-4285-af25-d29ea6dd66b4.png)

**Comment by WaynePhillipsEA** [comment] 2023-02-07 13:47
Is that with BETA 237?   There was a fix very recently for a problem with parsing when a space existed between the function name and the parameters.   e.g. `Split (a,b)` was being treated as `Split(a)` incorrectly.    The latest BETAs should not have that error.   Try removing the extra space character

**Comment by bodrusG** [comment] 2023-02-07 13:51
great ! its work fine ...   thanks ! ... tomorrow i wil ask you another question about dinamiclly load control ..

**Comment by WaynePhillipsEA** [comment] 2023-02-07 13:53
Great.  You're welcome.   The issue with the type library being generated in Standard EXE projects is also rectified in the next release later today, so the `Private Class` fix won't be needed once BETA 244 is out.

**Comment by WaynePhillipsEA** [comment] 2023-02-07 17:14
All fixed in BETA 244.  Thanks for reporting!

**Closed by WaynePhillipsEA** 2023-02-07 17:14 UTC
