### ISSUE TITLE
We are in the need to clone Wayne !

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1236] opened 2022-10-08 15:42 UTC
Problem : Just one Wayne currently availeable
Due the lack of time due user whishes we need more Wayne Power.

Solution: Develop some time travel device
Jump in the future, rob device,  clone Wayne at least 3 times 
:)

JOKE !

**Comment by WaynePhillipsEA** [comment] 2022-10-08 20:49
Yes that would be fun!  Haha

Now to ruin the party, and keep things fair, I'll have to close the issue ;)

**Closed by WaynePhillipsEA** 2022-10-08 20:49 UTC

**Comment by mwolfe02** [comment] 2022-10-10 02:58
I can't help but note that Wayne closed this issue with a status of "completed" as opposed to "won't implement" or "by design"... 

Which raises the question, _which_ Wayne closed this case as complete?  🤔
