### ISSUE TITLE
Issues with some keywords as procedure names

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#115] opened 2021-05-04 07:05 UTC
**Describe the bug**
The following piece of code does not work in a class.

```
Private PropName As String

Public Property Get Name() As String
Name = Left$(PropName, 100)
End Property
```

**Screenshots**
![image](https://user-images.githubusercontent.com/33756666/116970023-8416a000-acb7-11eb-9ef1-178f36554972.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.9.2311]

**Additional context**
it says for Left$ = missing argument for 'String'
for PropName it states = no handler for this symbol
The "Name" is colored blue, so I think it is not linking to the Property Value, thus causing the other errors as side-effect. (maybe)

**Comment by WaynePhillipsEA** [comment] 2021-05-04 07:22
Yes, this is a conflict with the Name syntax (which is not supported yet in tB, though the syntax is parsed).

A quick test shows that the following keywords are allowed in the same manner, despite being reserved syntax words:

   Reset
   Line
   Name
   Width
   Error

There may be others.

**Comment by bclothier** [comment] 2021-05-04 07:47
FWIW, those doesn't appear in the [reserved identifiers for MS-VBAL](https://docs.microsoft.com/en-us/openspecs/microsoft_general_purpose_programming_languages/ms-vbal/7df907cb-ab6c-40d3-aa81-272742ce00c3).

**Comment by WaynePhillipsEA** [comment] 2021-05-04 07:53
@bclothier Interesting, not reserved words technically then, despite being syntax statements.

The plot thickens. In VBA, if a function/property-get is called 'Reset' or 'Width', this also causes shadowing (hiding) of the Reset and Width statements within the whole class or module.

**Comment by Kr00l** [comment] 2021-08-17 18:20
`Event` and `RaiseEvent` are allowed in tB as method names. In VBx it throws a compile error.

Just quick question. Is it safe (no side-effects) when tB keeps allowing it?
Or is it better to restrict these like VBx is doing?

**Comment by wqweto** [comment] 2021-08-18 12:06
Btw, "shadowing" `Left` has dire consequences in TB

```
Module TestModule
    Private Function Left() As Single
        Left = 42
    End Function
    
    Public Sub Main()
        Dim s As String
        s = Left("This is a test", 4)
    End Sub
End Module
```

In VBx this compiles and runs as expected because (probably) `Left` w/ 2 params is handled as a spectacular exception in the parser.

I would suggest to generally support keying global symbol table resolution on name + number of parameters so that `Left` w/ no params differs `Left` w/ 1 param and `Left` w/ 2 params.

This would nicely extend the language while keeping backwards compatibility **while** handling exceptions like `VBA.Left` vs user-control's `Me.Left` property vs `Left` w/ one param custom function in BAS module.

**Comment by DaveInCaz** [comment] 2021-08-18 12:09
Implicit "shadowing" might be necessary for backwards compatibility, but would there also be some `Option xxx` which would instead result in errors for those cases? That would be a nice way to improve older code; first import it as-is and verify it works. Then gradually increase the level of strictness, using that to identify problems, and refactor as needed.

**Comment by Kr00l** [comment] 2021-08-29 10:30
There seems to be an issue to assign an Error named variable.
```
Dim Error As String
Error = "this fails, cannot assign"
```

**Comment by WaynePhillipsEA** [comment] 2021-08-29 10:51
@Kr00l yes, that's clashing with the Error statement syntax.  You can prefix with Let for now.

**Comment by WaynePhillipsEA** [comment] 2021-08-30 06:49
@Kr00l **_Error_** and **_Continue_** are now allowed as variable names as of v0.10.5165

**Comment by WaynePhillipsEA** [comment] 2023-06-02 06:25
I'm not able to reproduce any of the problems described in this issue in the latest releases of tB, therefore it's time to close this one.  Thanks all.

**Closed by WaynePhillipsEA** 2023-06-02 06:25 UTC
Labels: bug, confirmed
