### ISSUE TITLE
Expression fails when inside function

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1056] opened 2022-07-29 09:08 UTC
**Describe the bug**
An expression gives wrong result when it lives in a function.
Result is correct when e.g. in Sub Main.

**To Reproduce**
1. Load the attached.
[2022-07-29_WrongResult.zip](https://github.com/twinbasic/twinbasic/files/9218471/2022-07-29_WrongResult.zip)
3. Run.
4. Watch the the debug pane.

```
Option Explicit

Function IsIn(ByVal X1 As Double, ByVal Y1 As Double, ByVal X2 As Double, ByVal Y2 As Double, ByVal Tolerance As Double)

     Dim DX As Double, DY As Double

     IsIn = False

     DX = Abs(X1 - X2)
     If (DX > Tolerance) Then Exit Function

     DY = Abs(Y1 - Y2)
     If (DY > Tolerance) Then Exit Function

     IsIn = ((DX * DX) + (DY * DY) <= (Tolerance * Tolerance))

     Debug.Print "INSIDE IsIn = " & IsIn

End Function


Sub Main()

Dim X1 As Double
Dim Y1 As Double
Dim X2 As Double
Dim Y2 As Double
Dim Tolerance As Double

Dim OK As Boolean

X1 = 0
Y1 = 0
X2 = 0
Y2 = 0
Tolerance = 0.5

OK = IsIn(X1, Y1, X2, Y2, Tolerance)
Debug.Print "From IsIn OK = " & OK

OK = ((0 * 0) + (0 * 0) <= (Tolerance * Tolerance))
Debug.Print "Direct OK = " & OK

OK = ((0 * 0) + (0 * 0) <= (0.5 * 0.5))
Debug.Print "Direct OK2 = " & OK

OK = ((0) + (0) <= (0.5 * 0.5))
Debug.Print "Direct OK3 = " & OK

OK = ((0) <= (0.5 * 0.5))
Debug.Print "Direct OK4 = " & OK

OK = ((0) <= (0.25))
Debug.Print "Direct OK5 = " & OK

OK = (0 <= 0.25)
Debug.Print "Direct OK5 = " & OK

OK = 0 <= 0.25
Debug.Print "Direct OK6 = " & OK


End Sub
```

**Expected behavior**
Correct result.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC 86

**Additional context**

**Comment by KarlSevenSeven** [comment] 2022-07-29 09:24
I now see the IsIn function is Variant.
As Boolean makes no difference.

**Comment by WaynePhillipsEA** [comment] 2022-07-30 07:01
Fixed in BETA 88.  This was a regression caused by the changes to evaluation order in BETA 87.  Thanks for reporting.

**Closed by WaynePhillipsEA** 2022-07-30 07:01 UTC
