### ISSUE TITLE
Can not run x64 compiled apps.

### ISSUE THREAD

**Issue by GioKia** [twinbasic/twinbasic#1431] opened 2022-12-23 15:05 UTC
IDE beta 211, Laptop i7, Win 10 PRO, 22H2.

Standard EXE applications compiled in 64 bit do not run properly. 
It starts, without errors, and immediately they close, without showing any windows, messages or anything else.
Using the 32 bit compiler they work.
Old applications compiled in 64 bit with beta 210 work.
I reinstalled the beta 210 and everything works ;D

Thanks a lot
Gio

PS: I would like to have some example of use of classes, APIs and other components. Is there any public links? Thank you :)

**Comment by FullValueRider** [comment] 2022-12-23 15:34
Is this linked https://github.com/twinbasic/twinbasic/issues/1421

**Comment by WaynePhillipsEA** [comment] 2022-12-23 16:04
Fixed in BETA 211.   Apologies, this was caused by some teething issues on the new compilation server :)

**Closed by WaynePhillipsEA** 2022-12-23 16:04 UTC
