### ISSUE TITLE
native exception

### ISSUE THREAD

**Issue by bodrusG** [twinbasic/twinbasic#1530] opened 2023-03-27 07:45 UTC
hello I often have this error that happens very often. My project uses a com component written in vbnet, if I use the same component in another host or for example Excel I have no problem, but in twinbasic unfortunately it happens very often, is there anything I can do to avoid it? Thank you

![immagine](https://user-images.githubusercontent.com/124681792/227874638-a70cf2ed-78a4-4059-a929-62c2e77108c7.png)

**Comment by WaynePhillipsEA** [comment] 2023-03-27 15:43
Could you provide a minimal example that demonstrates the issue?

The exception code appears to be something to do with the .NET CLR garbage collection (EXCEPTION_HIJACK  0xE0434f4E), but I'd need to be able to reproduce the problem in order to fix it, since tB is only reporting it because the exception isn't being handled properly elsewhere.

**Comment by bodrusG** [comment] 2023-03-27 17:39
thank you for your attention, unfortunately it is a problem that I cannot consciously reproduce and therefore it is impossible for me to produce a minimal example. I must first find a way to reproduce it in a desired way, if I succeed in this regard I will send an example, thank you

**Comment by bodrusG** [comment] 2023-03-27 17:52
for now I can only show you what line 82 does

![immagine](https://user-images.githubusercontent.com/124681792/228025052-90662fe8-8020-4007-aad9-98ef41000108.png)

**Comment by fafalone** [comment] 2023-03-28 05:41
I think a lot of these are memory leak related, as they're popping up consistently, with more and more frequency the longer the IDE has been opened, and aren't possible to easily reproduce.

These are always the most insidious class of bugs... when a project reaches a certain level of complexity, you have random instabilities that are virtually impossible to track down and reproduce, because they're essentially random.

**Comment by WaynePhillipsEA** [comment] 2023-03-28 05:49
Indeed, they could simply be to do with the known memory leaks.  You could try turning on LargeAddressAware (LAA) in the IDE options (Tools menu > IDE Options...), and provided you have enough free RAM, that may reduce the problem until the memory leaks are fixed.   I am planning to look at the memory leaks very soon.

**Comment by bodrusG** [comment] 2023-03-28 06:31
Thanks, I'll try this suggestion

**Comment by WaynePhillipsEA** [comment] 2023-05-12 17:54
I'm wondering if this issue just got fixed in BETA 299.   I suspect the native exception will still get reported, but hopefully it no longer causes a restart of the debugging session.

**Comment by WaynePhillipsEA** [comment] 2023-06-02 19:28
Is this still an issue?

**Comment by bodrusG** [comment] 2023-06-03 16:06
I'm sorry, I couldn't verify because the project we were carrying out was suspended

**Comment by WaynePhillipsEA** [comment] 2023-06-03 16:09
No problem.  As we have no further information, well assume fixed.  Thanks

**Closed by WaynePhillipsEA** 2023-06-03 16:09 UTC
