### ISSUE TITLE
UDT not supported as parameter for functions with same name

### ISSUE THREAD

**Issue by AlanSkyNet** [twinbasic/twinbasic#1122] opened 2022-08-24 10:04 UTC
**Describe the bug**
You cannot use 2 custom types for functions with the same name but handling different custom types as parameter.
Error is duplicate definition in the current scope.

It works if the functions have the same name but handle string and integer parameter.

**Screenshots**
<img width="493" alt="customtype" src="https://user-images.githubusercontent.com/37843466/186390987-77edbdb8-f5fd-4b6c-a7fa-4dda9766c8a7.png">

<img width="404" alt="Simpletype" src="https://user-images.githubusercontent.com/37843466/186391047-a7c87c3e-6464-47bf-be68-fe39adc04788.png">

**Desktop (please complete the following information):**
 - OS: Windows 2019
 - twinBASIC compiler version 94

**Comment by WaynePhillipsEA** [comment] 2023-06-03 19:25
Dupe of #921

**Closed by WaynePhillipsEA** 2023-06-03 19:25 UTC
