### ISSUE TITLE
Compiled Console App says Debug

### ISSUE THREAD

**Issue by ja-rpms** [twinbasic/twinbasic#1679] opened 2023-09-08 14:35 UTC
**Describe the bug**
A compiled console application begins with the text "twinBasic Debugger Console..." and the subhead line "- debug sessions started at"

**To Reproduce**
1. Write a Console Application
2. Build it
3. Install the Exe
4. Run it to see the debug text

**Expected behavior**
Compiled version IMO should not have the words 'Debugger' or 'debug sessions'

**Screenshots**
![image](https://github.com/twinbasic/twinbasic/assets/104789993/8d10e325-5118-4151-a087-22323f47e0af)

**Desktop (please complete the following information):**
 - OS: Windows Server 2012
 - twinBASIC compiler version 0.15.337

**Additional context**
This is a very minor cosmetic issue - but it made me briefly believe I had missed a compilation switch and go searching for it. I thought it might do the same thing to other future developers.

**Comment by fafalone** [comment] 2023-09-08 16:13
Can't reproduce. 

Just a reminder, the blue start button and F5 run the exe with the twinBASIC debugger, where that is the expected output, as tB has a special debugger for console apps. If you build then use the Launch EXE link in the debug panel, or go to Explorer or command prompt and run from there, I'm not seeing the debugger message.

One issue I did notice though is the default sample code wipes, and then closes a preexisting command prompt when done, which isn't a desirable behavior, but I'll have to investigate if that's a bug or whether it needs to be coded different to avoid that.

**Comment by ja-rpms** [comment] 2023-09-08 17:05
Hello Jon,

Thanks for looking into this.

Here’s a video I made about what I’m seeing. This is on the dev machine itself, using Windows 11 Pro. I duplicated it when I installed the exe on a Windows 2012 Server.

https://vimeo.com/862472368/0e84fbef8c?share=copy

I’ve attached the project. I changed it to look for “calculatorapp.exe” which is the Windows 11 calculator – if you run it and it is running, it will kill it.  In order to make the project run on your machine, you’d have to put the name of your machine in place of where I’ve hard-coded “LAPTOP-TI990KF8”

Then, from a command prompt, run the executable with a ‘pause’ argument.  Or set up a shortcut to the exe with the pause argument like I did in the video.

If you can modify this build for your environment and it doesn’t display the debug info, I guess I need to figure out why mine does!

Thanks again.

Regards,

Jim Adam

**Comment by fafalone** [comment] 2023-09-09 03:42
That does indeed look weird. Can you try to attach the project again? It doesn't seem to have gone through however you did it.

I've verified the debug console does seem to get compiled into the final exe (at least those strings are present in an entirely different location than the other strings), so it is conceivable something's causing it to jump into that code, but it's just the presence of a 'pause' argument, I tried that with the basic console app.

**Comment by WaynePhillipsEA** [comment] 2023-09-09 06:13
Fixed in BETA 390.  Thanks!

**Closed by WaynePhillipsEA** 2023-09-09 06:13 UTC
