### ISSUE TITLE
Problems/Reports While Trying to Open my Game Project

### ISSUE THREAD

**Issue by vbBaka** [twinbasic/twinbasic#969] opened 2022-07-06 10:32 UTC
issue 1: 
UDT containing: **end As Integer** is not allowed

issue 2:
If --- Then Exit **Do Else** --- will require Do: or it will not work
same error also occurs with: 
If --- Then Exit **Sub Else** ---
If --- Then Exit **Function Else** ---
If --- Then GoTo **toEnd Else** ---

issue 3:
ReDim Preserve .Mission(**1 To** .missions)
I get the error: Expected operator between the operands
its inside a "with block" and it seems he doesnt like 1 To 

issue 4:
MiD = 1
using this as "variable" will conflict with the "Mid" function, so I get Invalid Mid Statement syntax.

issue 5:
Private Sub QuickSort(c() As Strin**g * 4**3, itm() As ItemData, ByVal first As Long, ByVal Last As Long, Optional ByVal Add&)
syntax error no handler for this symbol, and its "String *" that is complains about 

issue 6:
error:
I use it as "label" (from On Error GoTo error) so it seems "error" is reserved.

issue 7:
PROJECT ERROR: unable to load type library reference 'Direct2D1 for Visual Basic 6.0 type library by The trick v1.00'

**Comment by vbBaka** [comment] 2022-07-08 07:30
for issue 7.
in VB6 I only have 1, its called Direct2D1 for Visual Basic 6.0 type library by The trick v1.10
but in TB I have 2
Direct2D1 for Visual Basic 6.0 type library by The trick v1.00
Direct2D1 for Visual Basic 6.0 type library by The trick v1.10
and even if in my project I use v1.10, in TB it seems it tried to load v1.00

**Comment by WaynePhillipsEA** [comment] 2022-07-08 13:07
1 and 2 should be fixed in BETA 69.

**Comment by WaynePhillipsEA** [comment] 2022-07-09 05:52
Further to issue 4, the following variables are also problematic in tB at the moment due to conflicts with the same named statement syntax:
```
Dim mid : Mid = 123
Dim midb : MidB = 123
Dim reset : Reset = 123
Dim line : Line = 123
Dim width : Width = 123
```

`Width` is particularly interesting because the compiler repeatedly auto-corrects the `Width = 123` statement to `width = 123` and then back to `Width = 123` continuously, causing a lot of CPU usage and IDE sluggishness.

**Comment by WaynePhillipsEA** [comment] 2022-07-10 06:08
4 and 6 should be fixed in BETA 70.

Can't reproduce 3.

**Comment by vbBaka** [comment] 2022-07-10 07:36
with v70 the project can now be imported and the "infinite loop" is fixed. they resulted in more "problems"

issue 8:
inv_keyleftright **-1**
unexpected expression. if I use "1" it works, but not "-1"
the sub looks like this:
Sub inv_keyleftright(ByVal Add%, Optional ByVal Mode%)

issue 9:
**unload** doesn't exist

issue 10:
    With world(WorldIndex)
        .Bitmap = engine.LoadImage(FileName, , , .Width, .height)
        .top = top + 71
        .left = left + 80
        **.link.left = x1**
        **.link.top = y1**
        **.link.right = x2**
        **.link.bottom = y2**
        .Index = Index
    End With
expression neither used or assigned

and same with
With sys.
            .area.Width = res(Id).Width
            .area.height = res(Id).height
End With

issue 11:
With mobd(Index).Frame(c)
                engine.AddMob c, .Pos, **.left**, .right, .Rect, .Size, .BigLeft, .BigRight, .BigRECT
            End With
elements has errors

issue 12:
error in trying to call
Call Class_Initialize
inside a class (the Class_Initialize exist, I can use Call Class_Terminate)

**Comment by WaynePhillipsEA** [comment] 2022-07-11 04:51
There are a couple of things here that I can reproduce, so it might be easier to share the project so I can take a closer look.  e.g. this doesn't cause any problem in a new project for issue 8;

```
    Sub Test()
        inv_keyleftright -1
    End Sub

    Sub inv_keyleftright(ByVal Add%, Optional ByVal Mode%)
    End Sub
```

**Comment by WaynePhillipsEA** [comment] 2022-07-12 06:04
issue 8 is fixed in the next release coming later today.   Can't reproduce issue 10 or 11, please provide a full minimal example, or share the project for me to take a look.. Thanks.

**Comment by WaynePhillipsEA** [comment] 2022-07-12 15:55
Issues 8 and 9 are now fixed in BETA 72.  As you confirmed over in discord, issue 10 and 11 were fixed by one of the other fixes.

That leaves only issue 5, which is a lower priority issue.  I'm going to close this now and open a new issue for that.

Thanks for your help in reporting and tracking down the issues.

**Closed by WaynePhillipsEA** 2022-07-12 15:55 UTC
Labels: bug, confirmed, edge-cases
