### ISSUE TITLE
FundPtr and ResPtr

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1120] opened 2022-08-23 19:11 UTC
Same as the undocumented ones in VBA already there. To be able to call a sub or function by its address you need a hack. I am mad of having endless select case structures to call routines. With a function Pointer i could store them in a array and call them by a integer number. Imagein a drawing program. Each drawing entity has already a enum which holds a number of its type. In this case you could call the according draw routine by obtaining the according draw start address from the array structure. No select case anymore. OK it is not for "the weak". But on 3d programming you do not has friends - just a large crowd of enemy :)

**Comment by Kr00l** [comment] 2022-08-23 19:47
Duplicate of https://github.com/twinbasic/lang-design/issues/44

**Comment by fafalone** [comment] 2022-08-23 19:47
You can already do this with the DispCallFunc api
. It's not really a hack, just a fairly straightforward API call.

https://www.vbforums.com/showthread.php?863019-RESOLVED-Call-By-Address&p=5292509&viewfull=1#post5292509

tB removes many restrictions on AddressOf so you can easily make an array arAdr(i) = AddressOf func.

**Closed by Kr00l** 2022-08-23 19:47 UTC

**Comment by rexxitall** [comment] 2022-08-23 21:03
Thanks fafalone but are you sure that i would like to manage a call like this on daily usage ? Private Declare Function DispCallFunc Lib "oleaut32.dll" ( _
                         ByVal pvInstance As Long, _
                         ByVal FuncAddr As Long, _
                         ByVal CallConvention As Integer, _
                         ByVal rtnType As VbVarType, _
                         ByVal FuncArgsCnt As Long, _
                         ByRef FuncArgTypes As Any, _
                         ByRef FuncArgVarAddresses As Any, _
                         ByRef FuncResult As Any) As Long
For sure not :) And i do not like API calls for things like that. You can then waste endless time to find the api calls on each os and each bitness. And most problematic - those OS routines has no safety belts. They are made for speed. So such a thing should be build in without API :) But i love that you would help me out.  If some wants full speed he can use the api - on own risc :) There are a few of those hacks which i want to avoid in the future.  Those things i sometimes mention are usually not something THAT urgent. But something for fine polish later on. If i have a mission critical i will tell :) Be sure *laugh*

**Comment by bclothier** [comment] 2022-08-23 22:58
FWIW, You can use an abstraction layer over this. 

[Here's a TwinBasic implementation of UniversalCaller](https://github.com/bclothier/TwinBasicSevenZip/blob/96152be428f600b94c08ebaff1c4a8346c7b5e42/TwinProject/Sources/UniversalCaller.twin) and [a class that uses it internally](https://github.com/bclothier/TwinBasicSevenZip/blob/96152be428f600b94c08ebaff1c4a8346c7b5e42/TwinProject/Sources/LibraryManager.twin) to expose functions for the 7-Zip DLL's exported functions.
