### ISSUE TITLE
The custom property page of MSComctlLib.Toolbar is not shown fully

### ISSUE THREAD

**Issue by team-moeller** [twinbasic/twinbasic#1400] opened 2022-12-04 17:17 UTC
**Describe the bug**
The custom property page of MSComctlLib.Toolbar is not shown fully. It is a little bit too small.

**To Reproduce**
1. Insert Toolbar
2. Open custom property page

**Expected behavior**
All controls should be shown fully.

**Screenshots**
![image](https://user-images.githubusercontent.com/74451434/205505434-709dc186-7805-4599-a715-ebfc57cb8daa.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC IDE BETA 198

**Additional context**

**Comment by fafalone** [comment] 2022-12-05 03:18
What's not being shown? I checked in VB6 and don't see what's missing.

**Comment by WaynePhillipsEA** [comment] 2022-12-05 08:35
I think he means the tab frame is cutting off the right side of the controls slightly (e.g. combo boxes).   tB doesn't control the rendering of the property pages, but I suspect the issue is probably the very thick frame on the top level window that is seen in the screenshot.

If I remember rightly, this thick frame occurs when there is no VisualStyles manifest in the project.

**Comment by team-moeller** [comment] 2022-12-05 19:18
> I think he means the tab frame is cutting off the right side of the controls slightly (e.g. combo boxes)

Yes, that is exactly what I mean.

> If I remember rightly, this thick frame occurs when there is no VisualStyles manifest in the project.

Does that mean I can add something to the project and the problem goes away?

**Comment by fafalone** [comment] 2023-09-11 17:49
This seems to have gotten fixed somewhere along the lines so I'm closing this. Tried both with and without Visual Styles, dpi aware on and off for each, nothing was cut off anymore.

Please reopen or start new issue if recurring.

**Closed by fafalone** 2023-09-11 17:49 UTC
