### ISSUE TITLE
VSCode updating text with spurious characters

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#651] opened 2022-01-11 15:47 UTC
**Describe the bug**
This afternoon VSCode has started throwing another type of Wobbly.  This time it is transforming the previous couple of lines of text.  The typical pattern I'm seeing is that '.' and '(' are being substituted and some characters are being doubled up.

e.g. this

![OKChars](https://user-images.githubusercontent.com/81257042/148973649-28370b8f-8a2d-4be9-a1b4-c4760df56054.jpg)

becomes this

![SpuriousCharacters](https://user-images.githubusercontent.com/81257042/148973410-17a69265-711e-4999-a60d-a02b664da9d9.jpg)

**To Reproduce**
I've closed down VSCode and restarted several times but the problem persists.

**Expected behavior**
The editor behaves itself.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [see screenshots]

**Additional context**
I've attached the project and library I'm currently using.  I'm editing the Day04 class, the added library is my twinbasic  library which is finally passing all of its tests.

[twinBasic.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7847852/twinBasic.zip)
[TwinLib64v3_win64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7847856/TwinLib64v3_win64.zip)

**Comment by FullValueRider** [comment] 2022-01-11 18:05
More experience with this problem is showing that the spurious characters introduce are lowercase versions of the following character.  This is a weird one!!!

**Comment by WaynePhillipsEA** [comment] 2022-01-11 18:22
Apologies, I haven't had chance to look at this today.   Does turning off the 'Project: Auto Prettify Source Code' option in the project Settings help at all?

**Comment by FullValueRider** [comment] 2022-01-11 21:27
No Worries.  I've turned of the prettyfier and regret to say that the problems still occurs.  The substitutions occur when the text I've just typed/edited is analysed and colourised.

**Comment by FullValueRider** [comment] 2022-01-12 09:20
I'm afraid I'm going to have to stop using vscode/twinbasic until this issue is resolved.  At the moment, I have to edit every line of code at least twice.

I have deleted and reinstalled vscode.  The problem persists.
I have saved source files and recreated the activeX project.  The problem persists.
I have looked at an alternative twinBasic project. The problem is present there also.
VSCode project in another language (Nim) does not show this problem.

**Comment by WaynePhillipsEA** [comment] 2022-01-12 10:28
I'm struggling to reproduce the problem here.   Could you provide an exact edit that triggers the problem, using the files you provided?

**Comment by FullValueRider** [comment] 2022-01-12 10:42
IN The Day04 Module in the attached project

The code
```
Private Sub Initialise()
        
        If s.Data Is Nothing Then
        
            ' SPlit the raw data into two fields, list of drawn numbers, list of boards
            Set s.Data = _
                Lyst _  
                    .Deb _
                    .AddRange(VBA.Split(Filer.GetFileAsString(AoC2021Data & InputData), vbCrLf & vbCrLf, 2)) _
                    .Mapit(mpMultiReplace.Deb(Array(Char.twSpace & Char.twSpace, Char.twSpace), Array(vbCrLf & Char.twSpace, vbCrLf)))
```
delete the .Mapit
then retype .Mapit
click on a different line
I get
```
 Private Sub Initialise()
        
        If s.Data Is Nothing Then
        
            ' SPlit the raw data into two fields, list of drawn numbers, list of boards
            Set s.Data = _
                Lyst _  
                    .Deb _
                    .AddRange(VBA.Split(Filer.GetFileAsString(AoC2021Data & InputData), vbCrLf & vbCrLf, 2)) _
                    .mMapItmpMultiReplace.Deb(Array(Char.twSpace & Char.twSpace, Char.twSpace), Array(vbCrLf & Char.twSpace, vbCrLf)))
```
[TwinLib64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7853867/TwinLib64.zip)

**Comment by FullValueRider** [comment] 2022-01-12 11:02
BUT BUT BUT

If I Highlight .MapIt, Delete and retype .MapIt nothing happens when I click on another line
If I Highlight .MapIt, Delete and type .mapit I get spurious characters when I move to another line

**Comment by WaynePhillipsEA** [comment] 2022-01-12 11:05
That indicates that it indeed is something to do with the prettifier.   However.... I still can't repro

**Comment by WaynePhillipsEA** [comment] 2022-01-12 11:07
Could you try turning off the prettifier again for me?  With the prettifier set to 'No' it should not be auto-correcting the case of 'mapit' to 'Mapit' at all... and that switch seems to be working fine here.

**Comment by FullValueRider** [comment] 2022-01-12 11:14
It may be that I'm not turning off the prettyfier.  I'd assumed that if I set the Prettyfier to NO and then disabled it it would stay at no but this is not the case.  If I set the Prettyfier to NO and then disable the Prettyfier option, it defaults back to yes and I get the problem as described.  If I enable the Prettyfier and select no then the problem goes away.

**Comment by WaynePhillipsEA** [comment] 2022-01-12 11:16
Ah yes, I can understand the confusion there.  The tick means that you're overriding the setting from the inherited setting value (from the default settings in this case).  I do need to simplify the settings UX, so apologies for that.

Now we still need to find out what's causing the prettifier to get muddled up...

**Comment by FullValueRider** [comment] 2022-01-12 11:16
So I have a method for going forward even if the capitalisation gets a bit messy.

**Comment by WaynePhillipsEA** [comment] 2022-01-12 11:18
I noticed that this line is causing the prettifier a problem:
`s.answer += myHRank.nos.item(myIndex)`
Due to the internal exapnsion of the += operator, the prettifier tries to correct `s.answer` into `s.Answer` twice at the same document position, and VS code doesn't like that.

I'm not convinced that was causing your issue, but perhaps you could just check that for me?

**Comment by WaynePhillipsEA** [comment] 2022-01-12 11:19
Oh and this one:
`mycount += 1`  to `myCount += 1`

**Comment by FullValueRider** [comment] 2022-01-12 12:19
Sorry, can't be much help here. The line
```
s.answer += myHRank.nos.item(myIndex)
```
will likely show errors as I was refactoring and hadn't got to that point.  The method in which it sits had just been moved from Day04 to the Board class and was due to become 
```
answer += myHRank.item(myIndex)
```
There doesn't seem to be any issues with editing this line with the prettyfier on.

For 
```
mycount += 1 
```
which module was this in, I can't locate it in Day04.

**Comment by FullValueRider** [comment] 2022-01-13 17:17
Just to confirm that after a day's editing with the override for the prettyfier selected but the option set to off I've had no issues with spurious characters.  This is an OK position for me so to tracking down the prettyfier issue can be given a low priority from my perspective.

**Comment by WaynePhillipsEA** [comment] 2023-06-02 06:49
I've not seen any recent reports of this.  With it also being related to the older VS Code edition of tB, I'm inclined to close this now.  Thanks

**Closed by WaynePhillipsEA** 2023-06-02 06:49 UTC
Labels: bug, cant-repro
