### ISSUE TITLE
Allow ParamArray of types other than Variant()

### ISSUE THREAD

**Issue by mansellan** [twinbasic/twinbasic#1590] opened 2023-06-17 00:39 UTC
**Is your feature request related to a problem? Please describe.**
VBx only allows ParamArrays to be declared as an array of Variant. This seems to be an overly restrictive constraint, is it artificial?

**Describe the solution you'd like**
`Public Sub Find (ParamArray orderIds() As Long)`.

**Describe alternatives you've considered**
The status quo. Variants can hold anything, but that's both a strength and a weakness. It doesn't convey intent as precisely as a more defined type. Variants are also comparatively inefficient, which may be a problem in hot paths.

**Additional context**
I discussed this briefly in Discord, but still think it's worth raising a formal request to explore the idea. Not sure if this has COM implications, but I suspect it may do. Discussion invited.

Would also need to consider overload rules. What happens if both of these are defined?

`Public Sub Find (ParamArray orderIds() As Long)`
`Public Sub Find (ParamArray orderIds() As String)`

The resolver should be able to disambiguate, but I'm sure there are gotchas.

**Comment by Kr00l** [comment] 2023-07-02 18:50
Duplicate of https://github.com/twinbasic/lang-design/issues/15#issue-1317661817

**Closed by Kr00l** 2023-07-02 18:50 UTC

**Comment by mansellan** [comment] 2023-07-03 00:49
Oh dang, dupe of my own issue...

Sorry!
