### ISSUE TITLE
unable to resolve workspace folder

### ISSUE THREAD

**Issue by uwbwsvd** [twinbasic/twinbasic#273] opened 2021-07-11 15:44 UTC
**Describe the bug**
![grafik](https://user-images.githubusercontent.com/41230018/125201410-4e6dd480-e26f-11eb-9b28-4b5ae1e480be.png)

 - twinBASIC compiler version [v0.10.3423]

**Additional context**
I played around with vbrichclient RC6

**Comment by WaynePhillipsEA** [comment] 2021-07-11 16:02
If possible, please provide the twinproj file so that I can investigate this for you. Thanks

**Comment by uwbwsvd** [comment] 2021-07-11 16:41
[TwinBasic.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6797273/TwinBasic.zip)

**Comment by WaynePhillipsEA** [comment] 2021-07-11 17:27
Doesn't seem to reproduce here - tested both projects that you included.

**Comment by uwbwsvd** [comment] 2021-07-11 17:34
![grafik](https://user-images.githubusercontent.com/41230018/125204681-b7a91400-e27e-11eb-85c4-f64295cf9f62.png)
Changed this number, save, compile and so on. After some changes the message appeared.

**Comment by uwbwsvd** [comment] 2021-07-11 17:40
Can't reproduce it too. Must be something special.

**Comment by uwbwsvd** [comment] 2021-07-14 17:45
Got this error by testing this:
https://github.com/WaynePhillipsEA/twinbasic/issues/274#issue-944582014

![grafik](https://user-images.githubusercontent.com/41230018/125668031-d2edcd7c-a64f-40db-9aec-c72d2185be97.png)

**Comment by WaynePhillipsEA** [comment] 2021-07-14 17:54
Thanks.  Other than the warning message, does the project behave normally?

**Comment by uwbwsvd** [comment] 2021-07-14 18:03
No, the error describe at #274  does occur.

**Comment by WaynePhillipsEA** [comment] 2021-07-15 17:59
I think this is just a visual quirk.  It is indicating that something went wrong (i.e. the compiler crashed), but the compiler gets restarted automatically in the background and so you can continue to work as normal.

I will leave this open for now to review it at a later date to see if there's anything we can do inside the VS code extension to remove the problem indicator once the compiler has successfully restarted.

**Comment by mburns08109** [comment] 2021-08-25 04:04
I also saw weirdness here - my initial HelloWorld project somehow did not set up the project subfolders properly, and while it ran at first, a restart/reload subsequently ran into issues since the project folders were missing. So, perhaps there is a little bulletproofing code that needs to be added in this area?

**Comment by WaynePhillipsEA** [comment] 2021-08-25 04:43
@mburns08109 Hmm, that's weird.  I've not seen anything like that behaviour.   I'll dig around and see if I can spot what might've happened.   If it happens again for you, please make a copy of the broken twinproj file here for me to have a look.  Thanks

**Comment by WaynePhillipsEA** [comment] 2023-06-02 06:29
As this was a VS code specific issue, and it looks increasingly unlikely that we'll return to use VS Code in the near future, it's time to close this one.  Thanks.

**Closed by WaynePhillipsEA** 2023-06-02 06:29 UTC
Labels: low-priority, IDE quirk
