### ISSUE TITLE
MIDL throws errors when trying to compile twinBASIC-generated IDL 

### ISSUE THREAD

**Issue by kismert1** [twinbasic/twinbasic#1976] opened 2024-12-24 20:30 UTC
MIDL throws errors when trying to compile twinBASIC-generated IDL 
**To Reproduce**
 - Create a tB ActiveX dll
 - Export the IDL using OLEview
 - Try to compile the resulting IDL file using MIDL
 
**Expected behavior**
 - A successful MIDL compile which does not abort on error

**Desktop:**
 - OS: Windows 10 Pro 22H2
 - twinBASIC BETA 622

**Problem Examples**
Here are all the issues I have found so far (with suggested fixes):
# Problem #
Line continuations starting with '###'  throw an error. Example:
```
helpstring("Some text.
###
More text.
")
```
* Error:
C:\Projects\MIDL.IDL(11): error C2019: expected preprocessor directive, found '#'

* Fix:
Add \ before end of line:
```
helpstring("Some text.\
###\
More text.\
")
```
# Problem #
MIDL can't find MSACC.OLB and other references
```
importlib("MSACC.OLB");
```
* Error:
> C:\Projects\MIDL.IDL(13) : warning MIDL2015 : failed to load tlb in importlib: : MSACC.OLB

* Fix: 
I just prepended the path:
```
importlib("C:\Program Files (x86)\Microsoft Office\Office15\MSACC.OLB");
```
# Problem #
tB generated IDL throws errors when compiled by MIDL:
* tB Code:
```
    Option Compare Text
    Option Explicit

    Public Test1 As String
    Public Test2 As String
    Public Property Get Tests() As String
        Tests = Test1 & ", " & Test2
    End Property
```
* tB IDL:
```
    interface _Test_Error : IDispatch {
        [id(0x40030000), propget]
        HRESULT Test1([out, retval] BSTR* {retval});
        [id(0x40030000), propput]
        HRESULT Test1([in] BSTR {retval});
        [id(0x40030001), propget]
        HRESULT Test2([out, retval] BSTR* {retval});
        [id(0x40030001), propput]
        HRESULT Test2([in] BSTR {retval});
        [id(0x60030000), propget]
        HRESULT Tests([out, retval] BSTR* );
    };
```
* Errors: Each HRESULT line throws two errors:
> C:\Projects\MIDL.IDL(117) : error MIDL2025 : syntax error : expecting a declarator or * near "{"
> C:\Projects\MIDL.IDL(117) : error MIDL2025 : syntax error : expecting ) near "{"
# But This Works:
However, code similar to the above produces IDL that compiles successfully in MIDL:
* tB Code:
```
    Option Compare Text
    Option Explicit
    
    Private mstrTest1 As String
    Private mstrTest2 As String
    
    Public Property Get Test1() As String
        Test1 = mstrTest1
    End Property
    Public Property Let Test1(ByVal strTest As String)
        mstrTest1 = Test1
    End Property 
    Public Property Get Test2() As String
        Test2 = mstrTest2
    End Property
    Public Property Let Test2(ByVal strTest As String)
        mstrTest2 = Test2
    End Property
    Public Property Get Tests() As String
        Tests = mstrTest1 & ", " & mstrTest2
    End Property
```
* tB IDL:
```
    interface _Test_OK : IDispatch {
        [id(0x60030000), propget]
        HRESULT Test1([out, retval] BSTR* );
        [id(0x60030000), propput]
        HRESULT Test1([in] BSTR );
        [id(0x60030002), propget]
        HRESULT Test2([out, retval] BSTR* );
        [id(0x60030002), propput]
        HRESULT Test2([in] BSTR );
        [id(0x60030004), propget]
        HRESULT Tests([out, retval] BSTR* );
    };
```
* Errors: None

**Comment by WaynePhillipsEA** [comment] 2024-12-24 20:39
twinBASIC doesn't generate IDL.  It outputs a valid type library resource.   

The problems you are facing are either due to bad disassembly to IDL syntax, or MIDL compilation problems.  Neither of which are controlled by, or the fault of twinBASIC, so I'm going to close this issue.

**Comment by WaynePhillipsEA** [comment] 2024-12-24 20:50
Actually, the third problem, with tB using `{retval}` for the param name should be adjusted to match VBx, so I will reopen to get that adjusted.

**Comment by WaynePhillipsEA** [comment] 2024-12-29 08:18
The third issue has been rectified in BETA 627.   The other two problems are not problems with twinBASIC, but with the IDL disassembler that you're using, so I'm closing this issue.

**Closed by WaynePhillipsEA** 2024-12-29 08:18 UTC

**Comment by fafalone** [comment] 2024-12-29 10:46
oleview has not been modified since the 90s where midl has undergone numerous poorly documented or undocumented changes with little regard for backwards compatibility. Oleview can't even properly handle my oleexp.tlb, compiled with the truly ancient mktyplib; can't generate the complete idl; only show parts.

You need elaborate hacks and a specific midl version from the 90s to even compile vb/tb compatible tlbs with normal types and base interfaces; so not sure the goal.

**Comment by kismert1** [comment] 2025-01-03 20:55
All,
First, I hope you all had a restful holiday season.
@WaynePhillipsEA, @fafalone : Thanks for taking the time to explain the drawbacks of MIDL and OLEview. 
I will look for other ways to try to figure out why Access can't compile a tB ActiveX dll.
Any thoughts on how to proceed would be appreciated.
Thanks!

**Comment by fafalone** [comment] 2025-01-04 13:41
I thought Access couldn't compile anything? Just use compiled DLLs or ocxs in code executed by a p-code interpreter like other office apps.

Could you clarify in more detail exactly what you're trying to do and why it would involve trying to decompile and recompile typelibs?

**Comment by bclothier** [comment] 2025-01-04 14:37
I am assuming it's related to [this problem you reported in Discord](https://discord.com/channels/927638153546829845/1324959225503285309/1324959225503285309).

If that is the case and you're just using MIDL as workaround, I would not do that. While one can use MIDL to compile an arbitrary TLB and potentially redefine the signatures, you still are constrained to creating a compatible signature or it'll just blow up. 

A better workaround would be to use `Variant` instead which guarantees that your library is automation-compatible. Automation is much smaller subset of what is possible with COM, and tB supports a large subset of COM, but when making libraries for other clients, if you want to ensure maximum compatibility limiting to the Automation subset is the best way to achieve this. That is why several libraries will pass or receive a `Variant` or `Object` rather than a specific data type, particularly with arrays. That is also why UDTs are commonly avoided as a parameter/return in those libraries.

For more details on Automation, [look here](https://learn.microsoft.com/en-us/openspecs/windows_protocols/MS-OAUT/bbb05720-f724-45c7-8d17-f83c3d1a3961). 

However to avoid the error, as fafalone asked in the discord, we need a sample to reproduce the error so that it can be corrected or clarified.
