### ISSUE TITLE
Dorm can not get imported

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1304] opened 2022-10-25 12:33 UTC
**Describe the bug**
Attached Form get not imported and shows also not fake pictureboxes

Start a new exe Project and try to add the form.
[R.zip](https://github.com/twinbasic/twinbasic/files/9860238/R.zip)

**Comment by WaynePhillipsEA** [comment] 2022-10-25 17:01
You mean that you can't import the form into a VB6 project, in VB6, right?   Yeah, it reported errors for me too.  But unfortunately that's a VB6 issue, not a tB issue.

As such, I'm closing this on the basis that it's not tB related.

**Closed by WaynePhillipsEA** 2022-10-25 17:01 UTC

**Comment by rexxitall** [comment] 2022-10-25 17:34
I use that form in VB6 since weeks... I have no vb6 issues i have a TB issue :)

**Comment by WaynePhillipsEA** [comment] 2022-10-25 18:17
Then your opening message is cryptic ;)

tB doesn't currently offer the feature to import forms from FRM files individually, and since you have only provided the FRM file in the ZIP, and not the VBP, then I have to jump through hoops to try to reproduce the issue.   

I tried to import it into a new VB6 EXE project so that I can then import the VBP over to tB, but it failed to import to a new VBP project for me.   If you can provide a VBP along with the FRM, so that I can just do a simple import into tB, then hopefully I'll be able to see whatever issues you're experiencing.

**Comment by rexxitall** [comment] 2022-10-25 19:55
On such things just ask on discord :) The problem is in this case that the project is way mature state as what is shown in the zip file. For TB i try to make a very simple part of the whole project work. And i also do not know what is fully working in TB or what you need  :) So my idea was just to import the curent working form cause i was also curious how it looks like with the current implementation. I think this issue cam be closed until single form loading is done.
