### ISSUE TITLE
Shape control is displayed in front of some controls at runtime

### ISSUE THREAD

**Issue by marcoslm** [twinbasic/twinbasic#1526] opened 2023-03-13 19:16 UTC
**Describe the bug**
At runtime, the Shape control is displayed over some controls like Label and Image, even if we placed it behind them at design time.

**To Reproduce**
Simply place any of the mentioned controls overlapping a Shape control.

**Expected behavior**
The controls should look the same at runtime as they do at design time

**Screenshots**
![imagen](https://user-images.githubusercontent.com/2956806/224806113-a92365a0-7c25-4dbd-99a5-961d34129b01.png)
![imagen](https://user-images.githubusercontent.com/2956806/224806291-7f2b7db0-7236-4582-ad00-b4a4b8cae428.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC beta 270

[shape_control_overlap.zip](https://github.com/twinbasic/twinbasic/files/10960937/shape_control_overlap.zip)

**Comment by sokinkeso** [comment] 2023-03-13 19:25
The issue is that ,all lightweight controls (label, shape, line) are rendered in reverse Z-order at runtime.

**Comment by WaynePhillipsEA** [comment] 2023-03-14 15:26
Fixed in BETA 273, thanks!

**Closed by WaynePhillipsEA** 2023-03-14 15:26 UTC
