### ISSUE TITLE
How to build a form as it is seen in the IDE?

### ISSUE THREAD

**Issue by haplox** [twinbasic/twinbasic#1332] opened 2022-11-06 09:27 UTC
### Discussed in https://github.com/twinbasic/twinbasic/discussions/1328

<div type='discussions-op-text'>

<sup>Originally posted by **haplox** November  3, 2022</sup>
Hello all,

I do not know which property to change for the EXE file to be seen as in the IDE. I have a form designed, but when I build the EXE the form is extra large compared with the IDE.

How to acomodate the EXE file to be seen as in the IDE window?

Thanks in advance
![Sin título](https://user-images.githubusercontent.com/10757873/199708855-44df66e5-8477-4fec-ad64-5d643a168d19.jpg)
</div>

**Comment by fafalone** [comment] 2022-11-06 10:17
I can't find it now but you posted this once before with the project attached and I couldn't reproduce the issue.

![image](https://user-images.githubusercontent.com/7834493/200165339-49d0c33d-7859-4f3a-9b10-03b1e95a6dd6.png)

**Comment by WaynePhillipsEA** [comment] 2022-11-06 11:00
For reference here is the previous discussion:  https://github.com/twinbasic/twinbasic/discussions/1328

**Comment by WaynePhillipsEA** [comment] 2022-11-06 11:01
I can't repro in the IDE, but I can repro in a built EXE.

It looks to be a bug when you set controls Anchors Left/Top to False.  If you set the Left/Top to True, it resolves the issue until fixed.

**Comment by WaynePhillipsEA** [comment] 2022-11-07 07:06
Fixed in BETA 170.  Thanks!

**Closed by WaynePhillipsEA** 2022-11-07 07:06 UTC
