### ISSUE TITLE
Control Arrays do Not work, Index always 1

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1826] opened 2024-04-13 17:23 UTC
**Describe the bug**
Control Arrays do not work, 
After creating a new element with LOAD then setting any properties on that new element will instead apply to element(1)

**To Reproduce**
Put two textboxes on a form, Txb(1) and Txb(2).
In a Command button try to create and adjust a new element

Private Sub Command1_Click()

Load Txb(3)

Txb(1).Text = "11"
Txb(2).Text = "22"

Txb(3).Top = Txb(2).Top + Txb(2).Height + 20
Txb(3).Text = "3"
Txb(3).Visible = True
Txb(3).BackColor = vbRed

End Sub

>>>>>Txb(3) does not appear and its .text is applied to Txb(1)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version 502

**Comment by WaynePhillipsEA** [comment] 2024-04-16 05:57
Confirmed regression since BETA 423

**Comment by dmrvb** [comment] 2024-04-16 09:39
Re-open please??
Much much better but I think some properties still direct to element(1).
Will work on a this more to establish details..

**Comment by dmrvb** [comment] 2024-04-16 11:11
Put an array of two pictureboxes on a form.
Load two more at run time using LOAD.
they locate correctly (setting top property) and backcolor works ok.
but
Print "mytext" works on the design time pictureboxes, does not work on the new ones, it redirects to Pic(1).
mousemove and click events only work on the design times pictureboxes, not on the loaded ones (maybe this applies to all events?)
LostFocus and GotFocus do not work at all (maybe not yet implemented on any pictureboxes??)

Test Prog available if required

**Comment by WaynePhillipsEA** [comment] 2024-04-16 13:22
Should be fixed in BETA 508.  LostFocus/GotFocus may still be an issue.  Please open a new issue for them if needbe.  Thanks.

**Closed by WaynePhillipsEA** 2024-04-16 13:22 UTC

**Comment by dmrvb** [comment] 2024-04-16 14:27
Loks mostly good, Got/lostfocus not working
But but but.................,
Either I am going mad or you have done something daft
Any mousemove anywhere on a form in any project is sending out loads of "mousemove1 mousemove2" in the debug console.
So I reckon a bit of recent testcode has got compiled into your latest release?????

and I think the click event on the "loaded" controls is firing twice.

**Comment by WaynePhillipsEA** [comment] 2024-04-16 16:18
@dmrvb Yes, I am a plonker!

**Comment by WaynePhillipsEA** [comment] 2024-04-17 06:10
> and I think the click event on the "loaded" controls is firing twice.
Fixed in BETA 510, thanks

**Comment by dmrvb** [comment] 2024-04-17 09:47
Thanks,
Control Arrays are now working very well me. I might have some small issues but can't go further till you implement Got/LostFocus.
