### ISSUE TITLE
Unallocated module declared fixed arrays

### ISSUE THREAD

**Issue by wqweto** [twinbasic/twinbasic#1115] opened 2022-08-20 15:30 UTC
**Describe the bug**
Module declared fixed arrays seem to remain unallocated in compiled binaries but work ok in IDE.

**To Reproduce**
In Std-EXE project add a new module
```
' MyModule.twin
Module MyModule

    Private A(0 To 63) As Long
    
    Public Function Test() As Long
        Test = UBound(A)
    End Function

End Module
```
Form's code
```
    Private Sub Form_Click() Handles Form.Click
        MsgBox Test
    End Sub
```
When compiled clicking on the form bombs out with `Unspecified error` both in win32 and win64 release modes.

**Desktop (please complete the following information):**
 - OS: Win11
 - twinBASIC compiler version: BETA 96

**Comment by WaynePhillipsEA** [comment] 2022-08-23 06:41
This was a regression since BETA 91.   Fixed in BETA 97, thanks!

**Closed by WaynePhillipsEA** 2022-08-23 06:41 UTC
Labels: bug, confirmed
