### ISSUE TITLE
scope issue with assigned integer -1 returned as 0 in active X dll

### ISSUE THREAD

**Issue by AlanSkyNet** [twinbasic/twinbasic#1116] opened 2022-08-22 10:03 UTC
**Describe the bug**
A private integer is defined/assigned to -1 in a Module
A public function of the Module is used to return the value as an integer
When called from an ActiveX DLL, the value returned is 0 in the OnConnection event.

See the code in the screenshots below.

**Desktop (please complete the following information):**
 - OS: Windows 2019
 - twinBASIC compiler version build 94

**Screenshots**
![image002](https://user-images.githubusercontent.com/37843466/185894769-b0529cbc-1161-4d8c-9d76-0c1717eedc3c.png)

![image003](https://user-images.githubusercontent.com/37843466/185894836-f37007be-23c1-4752-898b-de762c8d0982.png)

**Comment by WaynePhillipsEA** [comment] 2022-08-22 10:09
Thanks for the report.  I believe there is a general issue with global variables not being initialized in generated EXEs/DLLs, in the latest builds of tB (presumably since the big codegen update in BETA 91 onwards).  I haven't looked at it yet, but am hoping to get it fixed later today.

Also related: #1115

**Comment by AlanSkyNet** [comment] 2022-08-22 13:36
Yes, I believe it was working in previous betas. Glad to know you're aware of it. Thanks for the great work on tB !!!

**Comment by WaynePhillipsEA** [comment] 2022-08-23 06:41
This was a regression since BETA 91.   Fixed in BETA 97, thanks!

**Closed by WaynePhillipsEA** 2022-08-23 06:41 UTC
Labels: bug, confirmed
